[package]
name = "storiny"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.1"
actix-cors = "0.6.4"
actix-extensible-rate-limit = { version = "0.2.1", features = ["redis"] }
actix-files = "0.6.2"
actix-http = "3.4.0"
actix-multipart = "0.6.1"
actix-redis = "0.13.0"
actix-request-identifier = "4.1.0"
actix-rt = "2.9.0"
actix-service = "2.0.2"
actix-test = "0.1.2"
actix-utils = "3.0.1"
actix-web = { version = "4.4.0", features = ["cookies", "secure-cookies"] }
actix-web-validator = "5.0.1"
anyhow = "1.0.75"
argon2 = "0.5.2"
async-trait = "0.1.73"
colors-transform = "0.2.11"
derive_more = "0.99.17"
dominant_color = "0.4.0"
dotenv = "0.15.0"
email_address = "0.2.4"
env_logger = "0.10.0"
futures-core = "0.3.28"
hashbrown = { version = "0.14.0", features = ["serde"] }
image = { version = "0.24.7", default-features = false, features = ["gif", "png", "jpeg", "jpeg_rayon", "webp", "webp-encoder"] }
lazy_static = "1.4.0"
log = "0.4.20"
maxminddb = "0.23.0"
mime = "0.3.17"
nanoid = "0.4.0"
pbjson = "0.6.0"
prost = "0.12.1"
rand = "0.8.5"
redis = { version = "0.23.3", features = ["tokio-comp", "aio", "connection-manager"] }
regex = "1.9.5"
rusoto_core = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_mock = "0.48.0"
rusoto_s3 = "0.48.0"
rusoto_ses = "0.48.0"
rusoto_signature = "0.48.0"
sailfish = "0.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
slugify = "0.1.0"
sqlx = { version = "0.7.2", features = ["postgres", "time", "macros", "json", "migrate", "runtime-tokio"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.48"
time = { version = "0.3.29", features = ["serde", "formatting", "macros"] }
tokio = "1.32.0"
tracing = "0.1.39"
url = "2.4.1"
user-agent-parser = "0.3.5"
uuid = { version = "1.4.1", features = ["v4"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
just = "1.14.0"
reqwest = { version = "0.11.22", default-features = false, features = ["cookies", "json"] }
