[package]
name = "storiny"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-extensible-rate-limit = { version = "0.2.1", features = ["redis"] }
actix-files = "0.6.2"
actix-http = "3.4.0"
actix-identity = "0.6.0"
actix-request-identifier = "4.1.0"
actix-rt = "2.9.0"
actix-test = "0.1.2"
actix-utils = "3.0.1"
actix-web = "4.4.0"
actix-web-validator = "5.0.1"
anyhow = "1.0.75"
argon2 = "0.5.2"
async-trait = "0.1.73"
derive_more = "0.99.17"
dotenv = "0.15.0"
env_logger = "0.10.0"
hashbrown = { version = "0.14.0", features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.20"
maxminddb = "0.23.0"
pbjson = "0.6.0"
prost = "0.12.1"
rand = "0.8.5"
redis = { version = "0.23.3", features = ["tokio-comp", "aio", "connection-manager"] }
regex = "1.9.5"
sailfish = "0.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
sqlx = { version = "0.7.2", features = ["postgres", "time", "macros", "json", "migrate", "runtime-tokio"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.48"
time = { version = "0.3.29", features = ["serde"] }
tokio = "1.32.0"
tracing = "0.1.39"
url = "2.4.1"
user-agent-parser = "0.3.5"
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
just = "1.14.0"
