version: "3.8"

services:
  geo:
    image: ghcr.io/maxmind/geoipupdate:v6.0
    container_name: "storiny-geoip"
    volumes:
      - ./db:/usr/share/GeoIP
    environment:
      GEOIPUPDATE_ACCOUNT_ID: "783964"
      GEOIPUPDATE_LICENSE_KEY: "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"
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
