[package]
name = "discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-governor = "0.4.1"
actix-http = "3.4.0"
actix-web = "4.4.0"
derive_more = "0.99.17"
dotenv = "0.15.0"
env_logger = "0.10.0"
just = "1.14.0"
lazy-regex = "3.0.1"
lazy_static = "1.4.0"
log = "0.4.20"
lz-str = "0.2.1"
once_cell = "1.18.0"
phf = { version = "0.11.2", features = ["macros"] }
regex-macro = "0.2.0"
serde = "1.0.188"
serde_json = "1.0.105"
url = "2.4.1"
