name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Import production web environment variables
        id: import-env
        shell: bash
        run: < apps/web/.env.production >> $GITHUB_ENV

#      # API
#      - name: Build, tag, and push api image
#        id: build-api-image
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        run: |
#          docker build \
#            --platform linux/amd64 \
#            -f apps/backend/Dockerfile \
#            -t $ECR_REGISTRY/storiny_api:latest apps/backend
#          docker push $ECR_REGISTRY/storiny_api:latest
#          echo "api-image=$ECR_REGISTRY/storiny_api:latest" >> $GITHUB_OUTPUT
#
#      # Nginx
#      - name: Build, tag, and push nginx image
#        id: build-nginx-image
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        run: |
#          docker build \
#            --platform linux/amd64 \
#            -f apps/cdn/nginx/Dockerfile \
#            -t $ECR_REGISTRY/storiny_nginx:latest apps/cdn/nginx
#          docker push $ECR_REGISTRY/storiny_nginx:latest
#          echo "nginx-image=$ECR_REGISTRY/storiny_nginx:latest" >> $GITHUB_OUTPUT
#
#      # Discovery
#      - name: Build, tag, and push discovery image
#        id: build-discovery-image
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        run: |
#          docker build \
#            --platform linux/amd64 \
#            -f apps/discovery/Dockerfile \
#            -t $ECR_REGISTRY/storiny_discovery:latest apps/discovery
#          docker push $ECR_REGISTRY/storiny_discovery:latest
#          echo "discovery-image=$ECR_REGISTRY/storiny_discovery:latest" >> $GITHUB_OUTPUT

      # Web
      - name: Build, tag, and push web image
        id: build-web-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/storiny_web:latest .
          docker push $ECR_REGISTRY/storiny_web:latest
          echo "web-image=$ECR_REGISTRY/storiny_web:latest" >> $GITHUB_OUTPUT

      - name: Recreate containers
        uses: appleboy/ssh-action@v1.0.0
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          envs: AWS_REGION,ECR_REGISTRY
          script: |
            aws ecr get-login-password \
              --region $AWS_REGION \
              | docker login \
              --username AWS \
              --password-stdin $ECR_REGISTRY
            docker-compose down
            docker system prune -a --volumes --force
            docker-compose up -d

      - name: Purge Cloudflare cache for static web assets
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
