name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Import production web environment variables
        id: import-env
        shell: bash
        run: < apps/web/.env.production >> $GITHUB_ENV

      # Web
#      - name: Build, tag, and push web image
#        id: build-web-image
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          docker build \
#            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
#            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
#            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
#            --platform linux/amd64 \
#            -t $ECR_REGISTRY/storiny_web:$IMAGE_TAG .
#          docker push $ECR_REGISTRY/storiny_web:$IMAGE_TAG
#          echo "web-image=$ECR_REGISTRY/storiny_web:$IMAGE_TAG" >> $GITHUB_OUTPUT

#      - name: Purge Cloudflare cache for static web assets
#        uses: jakejarvis/cloudflare-purge-action@v0.3.0
#        env:
#          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
#          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      # API
      - name: Build, tag, and push api image
        id: build-api-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64 -f apps/backend/Dockerfile -t $ECR_REGISTRY/storiny_api:$IMAGE_TAG .
          docker push $ECR_REGISTRY/storiny_api:$IMAGE_TAG
          echo "api-image=$ECR_REGISTRY/storiny_api:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Nginx
      - name: Build, tag, and push nginx image
        id: build-nginx-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64 -f apps/cdn/nginx/Dockerfile -t $ECR_REGISTRY/storiny_nginx:$IMAGE_TAG .
          docker push $ECR_REGISTRY/storiny_nginx:$IMAGE_TAG
          echo "nginx-image=$ECR_REGISTRY/storiny_nginx:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Discovery
      - name: Build, tag, and push discovery image
        id: build-discovery-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64 -f apps/discovery/Dockerfile -t $ECR_REGISTRY/storiny_discovery:$IMAGE_TAG .
          docker push $ECR_REGISTRY/storiny_discovery:$IMAGE_TAG
          echo "discovery-image=$ECR_REGISTRY/storiny_discovery:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # ECR cleanup. Deletes all the old images except the current one.
      # TODO: Increase the `qtd-images` field to keep at-least last two images for backup. We
      # currently only keep the latest image to remain under the 500MB limit of ECR for free plan.
      - name: Clean old web images
        uses: LeiaInc/devops-delete-old-aws-ecr-images@v1
        with:
          repo-name: $ECR_REGISTRY/storiny_web
          qtd-images: 1

      - name: Clean old api images
        uses: LeiaInc/devops-delete-old-aws-ecr-images@v1
        with:
          repo-name: $ECR_REGISTRY/storiny_api
          qtd-images: 1

      - name: Clean old nginx images
        uses: LeiaInc/devops-delete-old-aws-ecr-images@v1
        with:
          repo-name: $ECR_REGISTRY/storiny_nginx
          qtd-images: 1

      - name: Clean old discovery images
        uses: LeiaInc/devops-delete-old-aws-ecr-images@v1
        with:
          repo-name: $ECR_REGISTRY/storiny_discovery
          qtd-images: 1
